mockaroo:
  url: 'https://my.api.mockaroo.com/users.json'

supabase:
  bucketName: 'datalake'
  path_raw_data: 'crawler1'
  path_review_data : 'processed'

ollama:
  model_name: 'openhermes:7b-mistral-v2.5-q4_0'
  hostname: 'http://localhost:11434'
