mockaroo:
  url: 'https://my.api.mockaroo.com/users.json'

supabase:
  bucketName: 'datalake'
  path_raw_data:
    new: 'bronze/new'
    old: 'bronze/old'
  path_review_data : 'silver'

ollama:
  model_name: 'openhermes:7b-mistral-v2.5-q4_0'
  hostname: 'http://localhost:11434'
